### ISSUE TITLE
Getting Permissions Error when attempting to Execute: "Error: Cannot read configuration file due to insufficient permissions"

### ISSUE THREAD

**Issue by Tessando** [GeorgeSchiro/GetCert2#11]
I'm hitting a snag relating to Permissions. Are there any particular extra permissions necessary to give GetCert2.exe?

I did assign the local "IIS_IUSRS" with Read & Execute, but that didn't seem to help at all. Based on the small code snippet below, what permissions should I add in order to get GetCert2 to work as expected?

`2020-07-16 12:50:22:279 PM  GetCertServiceFault: Filename: redirection.config
Error: Cannot read configuration file due to insufficient permissions
   at Microsoft.Web.Administration.Interop.IAppHostAdminManager.GetAdminSection(String bstrSectionName, String bstrPath)
   at Microsoft.Web.Administration.Configuration.GetSectionInternal(ConfigurationSection section, String sectionPath, String locationPath)
   at Microsoft.Web.Administration.ServerManager.SitesSectionCreator()
   at Microsoft.Web.Administration.Lazy.Initialize[T](T& target, CreateInstanceDelegate`1 valueFactory)
   at Microsoft.Web.Administration.ServerManager.SitesCollectionCreator()
   at Microsoft.Web.Administration.Lazy.Initialize[T](T& target, CreateInstanceDelegate`1 valueFactory)
   at GetCert2.DoGetCert.VerifyDependencies(tvProfile aoProfile)
   at GetCert2.DoGetCert.oHandleUpdates(String[]& args, tvMessageBox& aoStartupWaitMsg)`

Thank you!

**Comment by GeorgeSchiro** [comment]
"Microsoft.Web.Administration.ServerManager" is the IIS library. The error implies that using the same security context as a user and running IIS manager should give you the same results .

So try that and let me know. Thanks!

**Comment by Tessando** [comment]
Yes! Thank you. I simply relaxed UAC, restarted and this fixed it. I appreciate the quick response. 

This is how I fixed it: https://social.technet.microsoft.com/wiki/contents/articles/13953.windows-server-2012-deactivating-uac.aspx

Thanks!
