### ISSUE TITLE
Running on IIS 2012 R2 I get an error uploading the certificate to IIS.

### ISSUE THREAD

**Issue by jimmymain** [GeorgeSchiro/GetCert2#15]
Is it possible to export the obtained certificate to a file and then import it manually into IIS?
I seem to have access problems with IIS.

I am running as Administrator and executed GetCert2 as administrator.

```
2021-08-03 08:45:26:921 AM  Bind certificate in IIS ...
2021-08-03 08:45:26:921 AM  Applying new certificate to "mysitename.co.za" site ...
2021-08-03 08:45:26:984 AM  ServiceFault: A specified logon session does not exist. It may already have been terminated
   at Microsoft.Web.Management.Utility.HttpApiWrapper.CreateSSLBinding(IPEndPoint endPoint, String hostName, HTTP_SERVICE_CONFIG_SSL_PARAM_MANAGED allSSLData, SslFlags sslFlags)
   at Microsoft.Web.Administration.BindingManager.BindingTransaction.Commit()
   at Microsoft.Web.Administration.BindingManager.Save()
   at Microsoft.Web.Administration.ServerManager.CommitChanges()
   at GetCert2.DoGetCert.bGetCertificate()
2021-08-03 08:45:26:999 AM  
2021-08-03 08:45:27:015 AM  At least one stage failed (or the process was stopped). Check log for errors.
2021-08-03 08:45:27:015 AM  

```

**Comment by GeorgeSchiro** [comment]
To answer your direct question Jim, using the **-CertificatePrivateKeyExportable** switch lets you export the certificate - with the private key included.

For example, you can run the software this way:

    GetCert2.exe -CertificatePrivateKeyExportable

Doing so enables the feature during that one run.

Alternatively, you can edit the profile file ("GetCert2.exe.config") and set the switch permanently like this:

    -CertificatePrivateKeyExportable=True

All that said, I would not recommend either as the correct solution. The above sidesteps the real issue, which would appear to be permissions, as you suggested.

Look into whatever account IIS (ie. "W3SVC") is running under (most likely "SYSTEM"). Whatever it is, make sure that account has access to your certificates.

Try binding the new certificate manually using IIS manager yourself. See if you get the same error.

**Comment by GeorgeSchiro** [comment]
Guess your all set Jim. Glad I could help! :0)
